# Generated by Django 3.2.3 on 2021-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('index', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(default=False, max_length=50)),
                ('name', models.CharField(default=False, max_length=20)),
                ('nick_name', models.CharField(default=False, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('login_type', models.CharField(default=False, max_length=20)),
                ('favorites_stadium', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '유저 정보 테이블',
                'db_table': 'user_info',
            },
        ),
    ]
